apiVersion: v2
name: wordpress
description: A Helm chart for WordPress with Composer
type: application
version: 0.1.0
appVersion: "6.4"
dependencies:
  - name: mariadb
    version: "11.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mariadb.enabled 